table circuits
	lineageTag: 7fc7fd11-7c32-407a-a887-4fedb94df5cc

	column circuit_id
		dataType: int64
		formatString: 0
		lineageTag: f864ebab-cbd6-404b-89da-87b89a0244a3
		summarizeBy: sum
		sourceColumn: circuit_id

		annotation SummarizationSetBy = Automatic

	column circuit_ref
		dataType: string
		lineageTag: 4bd7b81d-7fd0-4418-99c4-9ef4a78a38a2
		summarizeBy: none
		sourceColumn: circuit_ref

		annotation SummarizationSetBy = Automatic

	column circuit_name
		dataType: string
		lineageTag: 3fc18807-c877-4531-bc59-936010154c05
		summarizeBy: none
		sourceColumn: circuit_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: ca8ce6d5-4847-4cc0-8f62-c731f35ddb36
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 35bcc538-baca-4555-9e41-b2ff63768eaa
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: b2108bd1-2613-4268-a416-b46351366b16
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 2989f390-6b13-4d84-b21e-cab38a028796
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition circuits-ca589add-7b84-4b8d-8aca-0714a298c53a = m
		mode: import
		source =
				let
				    Source = Json.Document(File.Contents(SourceFiles & "circuits.json")),
				    #"Converted to Table" = Record.ToTable(Source),
				    #"Expanded Value" = Table.ExpandRecordColumn(#"Converted to Table", "Value", {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78"}, {"Value.0", "Value.1", "Value.2", "Value.3", "Value.4", "Value.5", "Value.6", "Value.7", "Value.8", "Value.9", "Value.10", "Value.11", "Value.12", "Value.13", "Value.14", "Value.15", "Value.16", "Value.17", "Value.18", "Value.19", "Value.20", "Value.21", "Value.22", "Value.23", "Value.24", "Value.25", "Value.26", "Value.27", "Value.28", "Value.29", "Value.30", "Value.31", "Value.32", "Value.33", "Value.34", "Value.35", "Value.36", "Value.37", "Value.38", "Value.39", "Value.40", "Value.41", "Value.42", "Value.43", "Value.44", "Value.45", "Value.46", "Value.47", "Value.48", "Value.49", "Value.50", "Value.51", "Value.52", "Value.53", "Value.54", "Value.55", "Value.56", "Value.57", "Value.58", "Value.59", "Value.60", "Value.61", "Value.62", "Value.63", "Value.64", "Value.65", "Value.66", "Value.67", "Value.68", "Value.69", "Value.70", "Value.71", "Value.72", "Value.73", "Value.74", "Value.75", "Value.76", "Value.77", "Value.78"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Value",{{"Name", type text}, {"Value.0", type any}, {"Value.1", type any}, {"Value.2", type any}, {"Value.3", type any}, {"Value.4", type any}, {"Value.5", type any}, {"Value.6", type any}, {"Value.7", type any}, {"Value.8", type any}, {"Value.9", type any}, {"Value.10", type any}, {"Value.11", type any}, {"Value.12", type any}, {"Value.13", type any}, {"Value.14", type any}, {"Value.15", type any}, {"Value.16", type any}, {"Value.17", type any}, {"Value.18", type any}, {"Value.19", type any}, {"Value.20", type any}, {"Value.21", type any}, {"Value.22", type any}, {"Value.23", type any}, {"Value.24", type any}, {"Value.25", type any}, {"Value.26", type any}, {"Value.27", type any}, {"Value.28", type any}, {"Value.29", type any}, {"Value.30", type any}, {"Value.31", type any}, {"Value.32", type any}, {"Value.33", type any}, {"Value.34", type any}, {"Value.35", type any}, {"Value.36", type any}, {"Value.37", type any}, {"Value.38", type any}, {"Value.39", type any}, {"Value.40", type any}, {"Value.41", type any}, {"Value.42", type any}, {"Value.43", type any}, {"Value.44", type any}, {"Value.45", type any}, {"Value.46", type any}, {"Value.47", type any}, {"Value.48", type any}, {"Value.49", type any}, {"Value.50", type any}, {"Value.51", type any}, {"Value.52", type any}, {"Value.53", type any}, {"Value.54", type any}, {"Value.55", type any}, {"Value.56", type any}, {"Value.57", type any}, {"Value.58", type any}, {"Value.59", type any}, {"Value.60", type any}, {"Value.61", type any}, {"Value.62", type any}, {"Value.63", type any}, {"Value.64", type any}, {"Value.65", type any}, {"Value.66", type any}, {"Value.67", type any}, {"Value.68", type any}, {"Value.69", type any}, {"Value.70", type any}, {"Value.71", type any}, {"Value.72", type any}, {"Value.73", type any}, {"Value.74", type any}, {"Value.75", type any}, {"Value.76", type any}, {"Value.77", type any}, {"Value.78", type any}}),
				    #"Transposed Table" = Table.Transpose(#"Changed Type"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"circuitId", Int64.Type}, {"circuitRef", type text}, {"name", type text}, {"location", type text}, {"country", type text}, {"lat", type number}, {"lng", type number}, {"alt", type text}, {"url", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"alt", "url"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"circuitId", "circuit_id"}, {"circuitRef", "circuit_ref"}, {"name", "circuit_name"}, {"location", "city"}, {"lat", "latitude"}, {"lng", "longitude"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

